### ISSUE TITLE
Help less-rails extend less.rb/less.js with additional functions.

### ISSUE THREAD

**Issue by metaskills** [cowboyd/less.rb#12]
I want to add additional functions to less.js for less-rails that would parse code like:

``` css
.rails {
  asset-path: asset-path("rails.png", image);
  asset-url: asset-url("rails.png", image);
  image-path: image-path("rails.png");
  image-url: image-url("rails.png");
  video-path: video-path("rails.mp4");
  video-url: video-url("rails.mp4");
  audio-path: audio-path("rails.mp3");
  audio-url: audio-url("rails.mp3");
  font-path: font-path("rails.ttf");
  font-url: font-url("rails.ttf");
  javascript-path: javascript-path("rails.js");
  javascript-url: javascript-url("rails.js");
  stylesheet-path: stylesheet-path("rails.css");
  stylesheet-url: stylesheet-url("rails.css");
  asset-data-url: asset-data-url("1x1.png");
}
```

I have this ticket on less-rails which describes my request for direction.
https://github.com/metaskills/less-rails/issues/1
